/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeinformacion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Adan
 */
public class crearCurso extends javax.swing.JFrame {
    
    Connection miConexion;
    /**
     * Creates new form crearCurso
     */
    public crearCurso(String user) {
        
        initComponents();
        usuario=user;
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        eti_codigoMateria = new javax.swing.JLabel();
        eti_nombreMateria = new javax.swing.JLabel();
        campoCodigoCurso = new javax.swing.JTextField();
        campoNomCurso = new javax.swing.JTextField();
        botonCrearCurso = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(240, 240, 240));
        Titulo.setText("CREAR CURSO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        eti_codigoMateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eti_codigoMateria.setForeground(new java.awt.Color(240, 240, 240));
        eti_codigoMateria.setText("Codigo para el curso:");
        getContentPane().add(eti_codigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        eti_nombreMateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eti_nombreMateria.setForeground(new java.awt.Color(240, 240, 240));
        eti_nombreMateria.setText("Nombre:");
        getContentPane().add(eti_nombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        campoCodigoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoCursoActionPerformed(evt);
            }
        });
        getContentPane().add(campoCodigoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        campoNomCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomCursoActionPerformed(evt);
            }
        });
        getContentPane().add(campoNomCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 200, -1));

        botonCrearCurso.setBackground(new java.awt.Color(0, 51, 255));
        botonCrearCurso.setForeground(new java.awt.Color(240, 240, 240));
        botonCrearCurso.setText("Crear curso");
        botonCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCursoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoCursoActionPerformed

    private void campoNomCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomCursoActionPerformed

    private void botonCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCursoActionPerformed
        
        
         try{
         //1 Crear Conexion 
          miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 preparar la consulta
         PreparedStatement miSentencia=miConexion.prepareStatement("INSERT INTO materia (codigo,nombre,usuario) VALUES (?,?,?)");
         //3 establecer parametros de la consulta
          miSentencia.setString(1,campoCodigoCurso.getText());
          miSentencia.setString(2,campoNomCurso.getText());
          miSentencia.setString(3,usuario);
         
          miSentencia.executeUpdate();
          JOptionPane.showMessageDialog(this,"Curso Creado");
         
        }catch(Exception error)
        {
            System.out.println("no se puede conectar a base de datos"+usuario);
        }
        
    }//GEN-LAST:event_botonCrearCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearCurso().setVisible(true);
            }
        });*/
    }

    public void ejecutar()
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    private String usuario; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonCrearCurso;
    private javax.swing.JTextField campoCodigoCurso;
    private javax.swing.JTextField campoNomCurso;
    private javax.swing.JLabel eti_codigoMateria;
    private javax.swing.JLabel eti_nombreMateria;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
