/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeinformacion;

import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author Adan
 */
public class InterfazDocente extends javax.swing.JFrame {

    Connection miConexion;
    /**
     * Creates new form InterfazDocente
     */
    public InterfazDocente(String nombre,String apellidos,String usuarioo) {
        eti_bienvenidaD = new javax.swing.JLabel();
        initComponents();
        this.setLocationRelativeTo(null);
        eti_bienvenidaD.setText("Bienvenido "+nombre+" "+apellidos);
        usuarioDocente=usuarioo;
        
        /*try
        {
            DefaultTableModel modelo=new DefaultTableModel();
            tablaCursos.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 creae objeto statement
            Statement miStatement=miConexion.createStatement();
            
            String sql="SELECT codigo,nombre FROM materia WHERE usuario=?";
            
            ps=miConexion.prepareStatement(sql);
            
            ps.setString(1,usuarioo);
            rs=ps.executeQuery();
            
            ResultSetMetaData rsMd=rs.getMetaData();
            
            int cantidadColumnas=rsMd.getColumnCount();
            
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre Materia");
            
            while(rs.next()){
                   Object[] filas=new Object[cantidadColumnas];
            
                  for(int i=0;i<cantidadColumnas;i++)
                     {
                         filas[i]=rs.getObject(i+1);
                     }
                 modelo.addRow(filas);
            }
           
        }catch(SQLException e)
        {
            System.out.println("error");
        }*/
        InterfazDocente();
        setVisible(true);
    }
    
    public void InterfazDocente()
    {
        try
        {
            DefaultTableModel modelo=new DefaultTableModel();
            tablaCursos.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 creae objeto statement
            Statement miStatement=miConexion.createStatement();
            
            String sql="SELECT codigo,nombre FROM materia WHERE usuario=?";
            
            ps=miConexion.prepareStatement(sql);
            
            ps.setString(1,usuarioDocente);
            rs=ps.executeQuery();
            
            ResultSetMetaData rsMd=rs.getMetaData();
            
            int cantidadColumnas=rsMd.getColumnCount();
            
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre Materia");
            
            while(rs.next()){
                   Object[] filas=new Object[cantidadColumnas];
            
                  for(int i=0;i<cantidadColumnas;i++)
                     {
                         filas[i]=rs.getObject(i+1);
                     }
                 modelo.addRow(filas);
            }
           
        }catch(SQLException e)
        {
            System.out.println("error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eti_bienvenidaD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eti_bienvenidaD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eti_bienvenidaD.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(eti_bienvenidaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 180, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Mis cursos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Crear curso nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, -1));

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre de la materia", "Opciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, 190));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Acualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        fondo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fondo.setForeground(new java.awt.Color(240, 240, 240));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        crearCurso c=new crearCurso(usuarioDocente);
        c.ejecutar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        InterfazDocente();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazDocente().setVisible(true);
            }
        });*/
        
    }
    
    public void ejecutar()
    {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }
    
    public String getUsuario()
    {
        return usuarioDocente;
    }
    
    private String usuarioDocente;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eti_bienvenidaD;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
